# Generated by Django 4.0.5 on 2022-06-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.core')),
                ('name', models.CharField(max_length=150)),
                ('carbs', models.FloatField(blank=True, default=0, null=True)),
                ('fiber', models.FloatField(blank=True, default=0, null=True)),
                ('sugar', models.FloatField(blank=True, default=0, null=True)),
                ('sodium', models.FloatField(blank=True, default=0, null=True)),
                ('protein', models.FloatField(blank=True, default=0, null=True)),
                ('calories', models.FloatField(blank=True, default=0, null=True)),
                ('total_fat', models.FloatField(blank=True, default=0, null=True)),
                ('trans_fat', models.FloatField(blank=True, default=0, null=True)),
                ('saturated_fat', models.FloatField(blank=True, default=0, null=True)),
            ],
            bases=('core.core',),
        ),
    ]
