# Generated by Django 4.0.5 on 2022-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Prefiro não Identificar')], default='3', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.CharField(choices=[('1', 'Bulking'), ('2', 'Cut'), ('3', 'Perda de Peso')], default='1', max_length=3),
        ),
    ]
